import { Poppins } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import connectDB from "@/services/connectDB";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Educonnect App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();

  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}

        <Toaster />
      </body>
    </html>
  );
}
